### ISSUE TITLE
Fix badly placed connection banner

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/FoGUWA#12]
On the map page when the connection is lost the banner is hidden by the search bar

**Comment by JeremiahPinto** [comment]
This is a good first issue for anyone wanting to get started on the project. Relatively harmless issue but a great intro to vue, nuxt and vuetify

**Comment by VicJohn447** [comment]
The vue stuff seems interesting so I'm gonna try and solve this issue.  Gonna smash out a few diagrams to help me and probably lots of questions on the discord and on Saturday.
