### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by JeremiahPinto** [codersforcauses/FoGUWA#15]
Add authentication for users using auth0. Ideally we use the default service they provide for a more secure interface. Will need to style said page to fit current theme.

A link to the page is also required at the bottom of the nav drawer

**Comment by Drewbi** [comment]
Should we use passport or implement it manually?

**Comment by JeremiahPinto** [comment]
It literally says auth0

**Comment by Drewbi** [comment]
[This](https://auth0.com/blog/node-js-and-express-tutorial-building-and-securing-restful-apis/) might be a helpful resource to follow.

**Comment by Drewbi** [comment]
So the plan with this one is:
- We have Auth0 giving us a [JWT](https://auth0.com/docs/jwt) 
- The client sends it to the backend through the login callback route
- The backend queries the Auth0 /userinfo endpoint to find the related email that the JWT is associated with. 
- The backend then checks to see if they are one of our authorised users
- If they are we can use [Express session](https://github.com/expressjs/session) to authorise them for a period of time

Interested in your thoughts/feedback @noobling @JeremiahPinto and anyone else
