### ISSUE TITLE
CRUD for users

### ISSUE THREAD

**Issue by Drewbi** [codersforcauses/FoGUWA#28]
Create, Read, Update and Delete controllers need to be added to the backend Users API.
They should be written in the routes/users.js file. The password field may need to be updated later depending on the implementation of Auth0 but for now treat it as a default string. 

You can check these off as you complete them:
- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by deanvains** [comment]
Similar situation to the Flora.js document, having issues with the creation and updating routes.
