### ISSUE TITLE
Admin edit flora

### ISSUE THREAD

**Issue by innocentmm** [codersforcauses/FoGUWA#39]
Dependent on the outcome of the Admin Roles issue. May be a good progression to work on the roles and then this due to the deep understanding you would have of the functionality here but can definitely be done by different people.   Key to this is ensuring that changes made by admin users (whether post approval or immediately by full access users) are reflected in the application. 

I will speak to FoG to finalise modifiable details but it should be plant information (so the text), location and click through link at the least. It is important to catch edge cases and ensure that regardless of the users input, if it is reasonable, it should be updated accordingly. 

Maybe develop methods to run background tests of the link before accepting and pushing changes?

**Comment by Drewbi** [comment]
The admins will need to: 
- [ ] Create markers with specified:
- Name
- Scientific name
- Description
- Images
- Icon choice (Out of those available)
- [ ] Update markers
- [ ] Delete markers
