### ISSUE TITLE
Admin help page

### ISSUE THREAD

**Issue by innocentmm** [codersforcauses/FoGUWA#40]
Quite simply, on this tab, we need to allow the users to send us requests to fix bugs etc on the admin page, it should go to hello@codersforcauses.org for now but we can set it up to either go to the technical lead or PMs if need be. Would be interesting to see if we could integrate it into GitHub to create an issue with the bug title as the issue title and description as the issue description base which we would then go in and modify

**Comment by Drewbi** [comment]
Documentation plus help page
